
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/zaheer-abbas/.strix/bin/"
      - "/home/zaheer-abbas/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/home/zaheer-abbas/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/home/zaheer-abbas/.nvm/versions/node/v22.23.2/bin/"
      - "/home/zaheer-abbas/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/snap/bin/"
      - "/home/zaheer-abbas/Android/Sdk/cmdline-tools/latest/bin/"
      - "/home/zaheer-abbas/Android/Sdk/platform-tools/"
    searched_directories:
      - "/home/zaheer-abbas/.strix/bin/uname"
      - "/home/zaheer-abbas/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/home/zaheer-abbas/.config/Code/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/home/zaheer-abbas/.nvm/versions/node/v22.23.2/bin/uname"
      - "/home/zaheer-abbas/.local/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/zaheer-abbas/.strix/bin"
        - "/home/zaheer-abbas/.config/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/home/zaheer-abbas/.config/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/home/zaheer-abbas/.strix/bin"
        - "/home/zaheer-abbas/.nvm/versions/node/v22.23.2/bin"
        - "/home/zaheer-abbas/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
        - "/snap/bin"
        - "/home/zaheer-abbas/.local/bin"
        - "/home/zaheer-abbas/.local/bin"
        - "/home/zaheer-abbas/Android/Sdk/cmdline-tools/latest/bin"
        - "/home/zaheer-abbas/Android/Sdk/platform-tools"
        - "/home/zaheer-abbas/.local/bin"
        - "/home/zaheer-abbas/Android/Sdk/cmdline-tools/latest/bin"
        - "/home/zaheer-abbas/Android/Sdk/platform-tools"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 7.0.0-30-generic - x86_64
...
